import type { MemoryAddRequest, RepairSuggestionRequest, ToolCallPayload, TurnCompleteRequest, TurnStartRequest } from "../../types.js";
import type { RawTurnRecord } from "../../storage/repositories.js";
import { buildPluginRetrievalQuery, isStandaloneMathFinalAnswerTask, STANDALONE_MATH_FINAL_ANSWER_TASK_KIND } from "../../algorithm/plugin-algorithms.js";
import { stableHash } from "../../utils/id.js";
import { isMemmyRecallToolName, memmyRecallToolPlaceholder, sanitizeMemmyProtocolText, sanitizeMemmyProtocolValue } from "../../utils/memmy-context-tags.js";

export interface NormalizedCompleteTurnArtifact { kind: string; uri?: string; payload: Record<string, unknown>; }

export function buildSearchQuery(request: TurnStartRequest, domain?: string): string { return buildPluginRetrievalQuery({ reason: "turn_start", userText: request.query, contextHints: request.contextHints, domain }).text; }
export function turnStartContextHints(request: TurnStartRequest): Record<string, unknown> { const hints = { ...(isRecord(request.contextHints) ? request.contextHints : {}) }; if (!hints.taskKind && isStandaloneMathFinalAnswerTask(request.query)) hints.taskKind = STANDALONE_MATH_FINAL_ANSWER_TASK_KIND; return hints; }
export function normalizeRetrievalExtractKeywords(value: unknown): string[] { if (!Array.isArray(value)) return []; const out: string[] = []; const seen = new Set<string>(); for (const item of value) { const keyword = String(item ?? "").trim(); const normalized = keyword.toLowerCase(); if (!keyword || seen.has(normalized)) continue; seen.add(normalized); out.push(keyword); if (out.length >= 5) break; } return out; }
export function buildRepairSuggestionQuery(request: RepairSuggestionRequest): string { const error = errorMessageFromUnknown(request.error); const pluginQuery = request.toolName ? buildPluginRetrievalQuery({ reason: "decision_repair", failingTool: request.toolName, failureCount: 1, lastErrorCode: error }).text : ""; return [pluginQuery, request.issue, error, request.context].filter(Boolean).join("\n"); }
export function sanitizeTurnStartRequest<T extends TurnStartRequest & Record<string, unknown>>(request: T): T { return { ...request, query: sanitizeMemmyProtocolText(String(request.query ?? "")) }; }
export function sanitizeTurnCompleteRequest<T extends TurnCompleteRequest & Record<string, unknown>>(request: T): T { const toolCalls = Array.isArray(request.toolCalls) ? request.toolCalls : []; return { ...request, query: sanitizeMemmyProtocolText(String(request.query ?? "")), answer: sanitizeMemmyProtocolText(String(request.answer ?? "")), toolCalls: Array.isArray(request.toolCalls) ? request.toolCalls.map(sanitizeMemmyProtocolValue) : request.toolCalls, toolResults: Array.isArray(request.toolResults) ? request.toolResults.map((result, index) => sanitizeCompleteTurnToolResult(result, toolNameFromToolCall(toolCalls[index]))) : request.toolResults }; }
export function sanitizeMemoryAddRequest<T extends MemoryAddRequest>(request: T): T { return { ...request, content: sanitizeMemmyProtocolText(request.content ?? ""), title: typeof request.title === "string" ? sanitizeMemmyProtocolText(request.title) : request.title }; }
export function completeObservedRawTurn(existing: RawTurnRecord, request: TurnCompleteRequest & Record<string, unknown>, completedAt: string): RawTurnRecord { const toolCalls = normalizeCompleteTurnToolCalls(request); const toolResults = normalizeCompleteTurnToolResults(request); return { ...existing, userText: request.query ?? existing.userText, assistantText: request.answer, reasoningSummary: stringFromMaybeRecord(request, "reasoningSummary") ?? existing.reasoningSummary, toolCalls: toolCalls.length ? toolCalls : existing.toolCalls, toolResults: toolResults.length ? toolResults : existing.toolResults, sourceMemoryIds: normalizeCompleteTurnSourceMemoryIds(request, existing.sourceMemoryIds), usage: isRecord(request.usage) ? request.usage : existing.usage, messagePayload: { ...(existing.messagePayload ?? {}), turn_complete: { completed_at: completedAt, source_memory_ids: normalizeCompleteTurnSourceMemoryIds(request, existing.sourceMemoryIds) } }, status: request.status ?? "succeeded" }; }
export function normalizeCompleteTurnSourceMemoryIds(request: TurnCompleteRequest & Record<string, unknown>, fallback: string[] = []): string[] { return Array.isArray(request.sourceMemoryIds) ? request.sourceMemoryIds.filter((value): value is string => typeof value === "string" && value.trim().length > 0) : fallback; }
export function normalizeCompleteTurnArtifacts(request: TurnCompleteRequest): NormalizedCompleteTurnArtifact[] { if (!Array.isArray(request.artifacts)) return []; return request.artifacts.map((artifact) => { if (!isRecord(artifact)) return null; const normalized: NormalizedCompleteTurnArtifact = { kind: stringFromRecord(artifact, "kind") ?? "artifact", payload: artifact }; const uri = stringFromRecord(artifact, "uri"); if (uri) normalized.uri = uri; return normalized; }).filter((artifact): artifact is NormalizedCompleteTurnArtifact => Boolean(artifact)); }
export function normalizeCompleteTurnToolCalls(request: TurnCompleteRequest): ToolCallPayload[] { const results = normalizeCompleteTurnToolResults(request); return (Array.isArray(request.toolCalls) ? request.toolCalls : []).map((call, index) => normalizeCompleteTurnToolCall(call, results[index])).filter((call): call is ToolCallPayload => Boolean(call)); }
export function normalizeCompleteTurnToolResults(request: TurnCompleteRequest): unknown[] { return Array.isArray(request.toolResults) ? request.toolResults : []; }
export function rawTurnIdForSessionTurn(sessionId: string, turnId: string): string { return `raw_${stableHash(`${sessionId}:${turnId}`).slice(0, 20)}`; }

function sanitizeCompleteTurnToolResult(value: unknown, pairedToolName: string | undefined): unknown { const toolName = toolNameFromToolResult(value) ?? pairedToolName; if (!isMemmyRecallToolName(toolName)) return sanitizeMemmyProtocolValue(value); const output: Record<string, unknown> = { name: toolName, output: memmyRecallToolPlaceholder(toolName) }; if (isRecord(value)) { const toolCallId = stringFromRecord(value, "toolCallId") ?? stringFromRecord(value, "tool_call_id") ?? stringFromRecord(value, "id"); if (toolCallId) output.toolCallId = toolCallId; } return output; }
function toolNameFromToolCall(value: unknown): string | undefined { if (!isRecord(value)) return undefined; const fn = isRecord(value.function) ? value.function : {}; return stringFromRecord(value, "name") ?? stringFromRecord(value, "toolName") ?? stringFromRecord(fn, "name"); }
function toolNameFromToolResult(value: unknown): string | undefined { return isRecord(value) ? stringFromRecord(value, "name") ?? stringFromRecord(value, "toolName") ?? stringFromRecord(value, "tool_name") : undefined; }
function normalizeCompleteTurnToolCall(value: unknown, pairedResult: unknown): ToolCallPayload | null { if (!isRecord(value)) return null; const fn = isRecord(value.function) ? value.function : {}; const name = stringFromRecord(value, "name") ?? stringFromRecord(fn, "name"); if (!name) return null; const result = isRecord(pairedResult) ? pairedResult : {}; const error = errorMessageFromUnknown(value.error) ?? errorMessageFromUnknown(result.error) ?? errorMessageFromUnknown(result.message); return { id: stringFromRecord(value, "id") ?? stringFromRecord(value, "call_id") ?? stringFromRecord(value, "tool_call_id"), name, input: firstDefined(value.input, value.args, value.arguments, fn.arguments), output: firstDefined(value.output, value.result, result.output, result.result, result.content, pairedResult), error, success: typeof value.success === "boolean" ? value.success : error ? false : undefined, startedAt: timeFromRecord(value, "startedAt") ?? timeFromRecord(value, "started_at"), endedAt: timeFromRecord(value, "endedAt") ?? timeFromRecord(value, "ended_at"), thinkingBefore: stringFromRecord(value, "thinkingBefore") ?? stringFromRecord(value, "thinking_before"), assistantTextBefore: stringFromRecord(value, "assistantTextBefore") ?? stringFromRecord(value, "assistant_text_before") }; }
function firstDefined(...values: unknown[]): unknown { return values.find((value) => value !== undefined && value !== null); }
function timeFromRecord(record: Record<string, unknown>, key: string): string | undefined { const value = record[key]; return typeof value === "string" && value.trim() ? value : undefined; }
function stringFromRecord(record: Record<string, unknown>, key: string): string | undefined { const value = record[key]; return typeof value === "string" ? value : undefined; }
function stringFromMaybeRecord(value: unknown, key: string): string | undefined { return isRecord(value) ? stringFromRecord(value, key) : undefined; }
function errorMessageFromUnknown(value: unknown): string | undefined { if (typeof value === "string" && value.trim()) return value.trim(); if (value instanceof Error) return value.message; return isRecord(value) ? stringFromRecord(value, "message") : undefined; }
function isRecord(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === "object" && !Array.isArray(value); }
