import type { IntegrationAuthKind } from "@memmy/local-api-contracts";

export interface IntegrationCatalogItem {
  slug: string;
  name: string;
  authKind: IntegrationAuthKind;
  authProvider?: string;
}

export const MANAGED_INTEGRATION_TOOLKITS: readonly IntegrationCatalogItem[] = Object.freeze([
  { slug: "airtable", name: "Airtable", authKind: "oauth" },
  { slug: "apaleo", name: "Apaleo", authKind: "oauth" },
  { slug: "asana", name: "Asana", authKind: "oauth" },
  { slug: "attio", name: "Attio", authKind: "oauth" },
  { slug: "basecamp", name: "Basecamp", authKind: "oauth" },
  { slug: "bitbucket", name: "Bitbucket", authKind: "oauth" },
  { slug: "blackbaud", name: "Blackbaud", authKind: "oauth" },
  { slug: "boldsign", name: "Boldsign", authKind: "oauth" },
  { slug: "box", name: "Box", authKind: "oauth" },
  { slug: "cal", name: "Cal", authKind: "oauth" },
  { slug: "calendly", name: "Calendly", authKind: "oauth" },
  { slug: "canva", name: "Canva", authKind: "oauth" },
  { slug: "capsule_crm", name: "Capsule CRM", authKind: "oauth" },
  { slug: "clickup", name: "ClickUp", authKind: "oauth" },
  { slug: "confluence", name: "Confluence", authKind: "oauth" },
  { slug: "contentful", name: "Contentful", authKind: "oauth" },
  { slug: "convex", name: "Convex", authKind: "oauth" },
  { slug: "crowdin", name: "Crowdin", authKind: "oauth" },
  { slug: "dart", name: "Dart", authKind: "oauth" },
  { slug: "dialpad", name: "Dialpad", authKind: "oauth" },
  { slug: "digital_ocean", name: "DigitalOcean", authKind: "oauth" },
  { slug: "discord", name: "Discord", authKind: "oauth" },
  { slug: "discordbot", name: "Discord Bot", authKind: "oauth" },
  { slug: "dropbox", name: "Dropbox", authKind: "oauth" },
  { slug: "dub", name: "Dub", authKind: "oauth" },
  { slug: "dynamics365", name: "Dynamics 365", authKind: "oauth" },
  { slug: "eventbrite", name: "Eventbrite", authKind: "oauth" },
  { slug: "excel", name: "Excel", authKind: "oauth" },
  { slug: "exist", name: "Exist", authKind: "oauth" },
  { slug: "facebook", name: "Facebook", authKind: "oauth" },
  { slug: "fathom", name: "Fathom", authKind: "oauth" },
  { slug: "figma", name: "Figma", authKind: "oauth" },
  { slug: "freeagent", name: "Freeagent", authKind: "oauth" },
  { slug: "freshbooks", name: "FreshBooks", authKind: "oauth" },
  { slug: "github", name: "GitHub", authKind: "oauth" },
  { slug: "gitlab", name: "GitLab", authKind: "oauth" },
  { slug: "gmail", name: "Gmail", authKind: "oauth" },
  { slug: "googleads", name: "Google Ads", authKind: "oauth" },
  { slug: "google_analytics", name: "Google Analytics", authKind: "oauth" },
  { slug: "googlebigquery", name: "Google BigQuery", authKind: "oauth" },
  { slug: "googlecalendar", name: "Google Calendar", authKind: "oauth" },
  { slug: "google_classroom", name: "Google Classroom", authKind: "oauth" },
  { slug: "googledocs", name: "Google Docs", authKind: "oauth" },
  { slug: "googledrive", name: "Google Drive", authKind: "oauth" },
  { slug: "google_maps", name: "Google Maps", authKind: "oauth" },
  { slug: "googlemeet", name: "Google Meet", authKind: "oauth" },
  { slug: "googlephotos", name: "Google Photos", authKind: "oauth" },
  { slug: "google_search_console", name: "Google Search Console", authKind: "oauth" },
  { slug: "googlesheets", name: "Google Sheets", authKind: "oauth" },
  { slug: "googleslides", name: "Google Slides", authKind: "oauth" },
  { slug: "googlesuper", name: "Google Super", authKind: "oauth" },
  { slug: "googletasks", name: "Google Tasks", authKind: "oauth" },
  { slug: "gorgias", name: "Gorgias", authKind: "oauth" },
  { slug: "gumroad", name: "Gumroad", authKind: "oauth" },
  { slug: "harvest", name: "Harvest", authKind: "oauth" },
  { slug: "hubspot", name: "HubSpot", authKind: "oauth" },
  { slug: "hugging_face", name: "Hugging Face", authKind: "oauth" },
  { slug: "instagram", name: "Instagram", authKind: "oauth" },
  { slug: "intercom", name: "Intercom", authKind: "oauth" },
  { slug: "jira", name: "Jira", authKind: "oauth" },
  { slug: "kit", name: "Kit", authKind: "oauth" },
  { slug: "linear", name: "Linear", authKind: "oauth" },
  { slug: "linkedin", name: "LinkedIn", authKind: "oauth" },
  { slug: "linkhut", name: "Linkhut", authKind: "oauth" },
  { slug: "mailchimp", name: "Mailchimp", authKind: "oauth" },
  { slug: "microsoft_teams", name: "Microsoft Teams", authKind: "oauth" },
  { slug: "miro", name: "Miro", authKind: "oauth" },
  { slug: "monday", name: "Monday", authKind: "oauth" },
  { slug: "moneybird", name: "Moneybird", authKind: "oauth" },
  { slug: "mural", name: "Mural", authKind: "oauth" },
  { slug: "notion", name: "Notion", authKind: "oauth" },
  { slug: "omnisend", name: "Omnisend", authKind: "oauth" },
  { slug: "one_drive", name: "OneDrive", authKind: "oauth" },
  { slug: "outlook", name: "Outlook", authKind: "oauth" },
  { slug: "pagerduty", name: "PagerDuty", authKind: "oauth" },
  { slug: "prisma", name: "Prisma", authKind: "oauth" },
  { slug: "productboard", name: "Productboard", authKind: "oauth" },
  { slug: "pushbullet", name: "Pushbullet", authKind: "oauth" },
  { slug: "quickbooks", name: "QuickBooks", authKind: "oauth" },
  { slug: "reddit", name: "Reddit", authKind: "oauth" },
  { slug: "reddit_ads", name: "Reddit Ads", authKind: "oauth" },
  { slug: "roam", name: "Roam", authKind: "oauth" },
  { slug: "salesforce", name: "Salesforce", authKind: "oauth" },
  { slug: "sentry", name: "Sentry", authKind: "oauth" },
  { slug: "servicem8", name: "Servicem8", authKind: "oauth" },
  { slug: "share_point", name: "SharePoint", authKind: "oauth" },
  { slug: "shippo", name: "Shippo", authKind: "oauth" },
  { slug: "slack", name: "Slack", authKind: "oauth" },
  { slug: "slackbot", name: "Slackbot", authKind: "oauth" },
  { slug: "splitwise", name: "Splitwise", authKind: "oauth" },
  { slug: "square", name: "Square", authKind: "oauth" },
  { slug: "stack_exchange", name: "Stack Exchange", authKind: "oauth" },
  { slug: "strava", name: "Strava", authKind: "oauth" },
  { slug: "stripe", name: "Stripe", authKind: "oauth" },
  { slug: "supabase", name: "Supabase", authKind: "oauth" },
  { slug: "ticketmaster", name: "Ticketmaster", authKind: "oauth" },
  { slug: "ticktick", name: "Ticktick", authKind: "oauth" },
  { slug: "timely", name: "Timely", authKind: "oauth" },
  { slug: "todoist", name: "Todoist", authKind: "oauth" },
  { slug: "toneden", name: "Toneden", authKind: "oauth" },
  { slug: "trello", name: "Trello", authKind: "oauth" },
  { slug: "typeform", name: "Typeform", authKind: "oauth" },
  { slug: "wakatime", name: "WakaTime", authKind: "oauth" },
  { slug: "webex", name: "Webex", authKind: "oauth" },
  { slug: "whatsapp", name: "WhatsApp Business", authKind: "oauth" },
  { slug: "wrike", name: "Wrike", authKind: "oauth" },
  { slug: "yandex", name: "Yandex", authKind: "oauth" },
  { slug: "ynab", name: "YNAB", authKind: "oauth" },
  { slug: "youtube", name: "YouTube", authKind: "oauth" },
  { slug: "zendesk", name: "Zendesk", authKind: "oauth" },
  { slug: "zoho", name: "Zoho", authKind: "oauth" },
  { slug: "zoho_bigin", name: "Zoho Bigin", authKind: "oauth" },
  { slug: "zoho_books", name: "Zoho Books", authKind: "oauth" },
  { slug: "zoho_desk", name: "Zoho Desk", authKind: "oauth" },
  { slug: "zoho_inventory", name: "Zoho Inventory", authKind: "oauth" },
  { slug: "zoho_invoice", name: "Zoho Invoice", authKind: "oauth" },
  { slug: "zoho_mail", name: "Zoho Mail", authKind: "oauth" },
  { slug: "zoom", name: "Zoom", authKind: "oauth" }
]);

export const ALL_INTEGRATION_CATALOG: readonly IntegrationCatalogItem[] = MANAGED_INTEGRATION_TOOLKITS;
